# Generated by Django 4.2.4 on 2023-08-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.CharField(max_length=100)),
                ('senha_cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camisa_venda', models.ImageField(upload_to='static/assets/img')),
            ],
        ),
    ]
